apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-cy
  name: nginx-cy
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-cy
  type: {{ .Values.service.type }}
